### ISSUE TITLE
No testHelper.js file

### ISSUE THREAD

**Issue by PreetiRS** [learn-co-curriculum/phase-1-first-class-functions#1]
"learn" command throws an error. Likely because there is no testHelp.js file if that is what brings fails up.

**Comment by lizbur10** [comment]
Hello @PreetiRS! Thanks for spotting this issue and posting feedback! The error was caused by a node module version conflict and should now be fixed. If you copy the contents of the package.json file from this GitHub repo and paste it into your local copy of the file then rerun npm install, it should work. If you continue to have problems, please reopen this issue.

Thanks! 💙
